import 'dart:io';
import 'package:flutter/cupertino.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:my_gallery/core/routing/routes.dart';
import 'package:my_gallery/features/gallery/bloc/gallery_cubit.dart';
import 'package:my_gallery/features/gallery/screens/gallery_screen.dart';
import 'package:my_gallery/features/login/bloc/login_cubit.dart';
import 'package:my_gallery/features/login/screens/login_screen.dart';
part 'router.main.dart';
